In [2]:
import pandas as pd
import numpy as np

## Make MA_{ma} columns

In [3]:
intervals = ['1h', '2h', '4h', '12h', '1d']
# intervals = ['1h']
for interval in intervals:
    btc_data = pd.read_csv(f'data/btc_all_{interval}_candles_from_2017.csv')
    ma_candidates = [10, 20, 30, 50, 60, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 1000, 1010, 1020, 1030, 1040, 1050, 1060]
    # Calculate moving averages for each candidate
    for ma in ma_candidates:
        btc_data[f'MA_{ma}'] = btc_data['close'].rolling(window=ma).mean()
    btc_data.to_csv(f'data/btc_{interval}_data_with_ma.csv', index=False)

In [4]:

# Display the first few rows of the updated DataFrame
print(btc_data.head(50))

     timestamp     open     high      low    close       volume     MA_10  \
0   2017-08-17  4261.48  4485.39  4200.74  4285.08   795.150377       NaN
1   2017-08-18  4285.08  4371.52  3938.77  4108.37  1199.888264       NaN
2   2017-08-19  4108.37  4184.69  3850.00  4139.98   381.309763       NaN
3   2017-08-20  4120.98  4211.08  4032.62  4086.29   467.083022       NaN
4   2017-08-21  4069.13  4119.62  3911.79  4016.00   691.743060       NaN
5   2017-08-22  4016.00  4104.82  3400.00  4040.00   966.684858       NaN
6   2017-08-23  4040.00  4265.80  4013.89  4114.01  1001.136565       NaN
7   2017-08-24  4147.00  4371.68  4085.01  4316.01   787.418753       NaN
8   2017-08-25  4316.01  4453.91  4247.48  4280.68   573.612740       NaN
9   2017-08-26  4280.71  4367.00  4212.41  4337.44   228.108068  4172.386
10  2017-08-27  4332.51  4400.00  4285.54  4310.01   350.692585  4174.879
11  2017-08-28  4310.01  4399.82  4124.54  4386.69   603.841616  4202.711
12  2017-08-29  4353.65  4625.85  4313.55  4587.48   603.545028  4247.461
13  2017-08-30  4564.52  4647.51  4416.01  4555.14   808.468771  4294.346
14  2017-08-31  4555.14  4745.42  4555.14  4724.89   556.956802  4365.235
15  2017-09-01  4689.89  4885.55  4654.88  4834.91   560.666366  4444.726
16  2017-09-02  4796.16  4939.19  4286.87  4472.14   929.148595  4480.539
17  2017-09-03  4508.50  4714.76  4298.33  4509.08   691.216198  4499.846
18  2017-09-04  4505.00  4527.49  3972.51  4100.11  1394.644614  4481.789
19  2017-09-05  4106.97  4484.99  3603.00  4366.47  1228.938157  4484.692
20  2017-09-06  4366.49  4662.87  4335.26  4619.77   807.363726  4515.668
21  2017-09-07  4619.77  4788.59  4438.19  4691.61   500.429975  4546.160
22  2017-09-08  4691.66  4735.39  4028.93  4282.80  1132.255046  4515.692
23  2017-09-09  4282.80  4426.62  4150.06  4258.81   658.782952  4486.059
24  2017-09-10  4258.81  4283.00  3801.00  4130.37   660.373275  4426.607
25  2017-09-11  4153.62  4334.43  4098.91  4208.47   699.989065  4363.963
26  2017-09-12  4208.60  4394.59  4040.80  4163.72   879.630319  4333.121
27  2017-09-13  4159.72  4165.38  3760.00  3944.69   913.462545  4276.682
28  2017-09-14  3944.00  3993.00  3165.13  3189.02  1665.021543  4185.573
29  2017-09-15  3188.01  3856.00  2817.00  3700.00  1968.866492  4118.926
30  2017-09-16  3674.01  3950.00  3470.66  3714.95  1297.563953  4028.444
31  2017-09-17  3685.23  3748.21  3499.02  3699.99   682.171210  3929.282
32  2017-09-18  3690.00  4123.20  3690.00  4035.01  1030.006455  3904.503
33  2017-09-19  4060.00  4089.97  3830.91  3910.04   902.332129  3869.626
34  2017-09-20  3910.04  4046.08  3820.00  3900.00   720.935076  3846.589
35  2017-09-21  3889.99  3910.00  3567.00  3609.99  1001.654084  3786.741
36  2017-09-22  3592.84  3750.00  3505.55  3595.87   838.966425  3729.956
37  2017-09-23  3595.88  3817.19  3542.91  3780.00   752.792791  3713.487
38  2017-09-24  3779.54  3789.99  3622.76  3660.02   661.636390  3760.587
39  2017-09-25  3660.02  3979.87  3653.69  3920.75   727.994713  3782.662
40  2017-09-26  3928.00  3976.99  3850.05  3882.35   526.727987  3799.402
41  2017-09-27  3882.36  4249.94  3872.81  4193.00   628.170966  3848.703
42  2017-09-28  4192.11  4300.00  4101.00  4174.50   849.785325  3862.652
43  2017-09-29  4178.98  4263.86  3952.01  4174.69  1602.309565  3889.117
44  2017-09-30  4175.00  4380.00  4138.10  4378.51   720.353183  3936.968
45  2017-10-01  4378.49  4406.52  4240.04  4378.48   726.963685  4013.817
46  2017-10-02  4400.00  4561.63  4360.00  4380.00   655.756974  4092.230
47  2017-10-03  4380.00  4467.33  4180.80  4310.00  1082.323563  4145.230
48  2017-10-04  4314.90  4373.00  4142.00  4208.59   868.465101  4200.087
49  2017-10-05  4208.59  4355.00  4110.00  4292.43   779.138638  4237.255

        MA_20        MA_30      MA_50  ...  MA_540  MA_550  MA_560  MA_1000  \
0         NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
1         NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
2         NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
3         NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
4         NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
5         NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
6         NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
7         NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
8         NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
9         NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
10        NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
11        NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
12        NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
13        NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
14        NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
15        NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
16        NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
17        NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
18        NaN          NaN        NaN  ...     NaN     NaN     NaN      NaN
19  4328.5390          NaN        NaN  ...     NaN     NaN     NaN      NaN
20  4345.2735          NaN        NaN  ...     NaN     NaN     NaN      NaN
21  4374.4355          NaN        NaN  ...     NaN     NaN     NaN      NaN
22  4381.5765          NaN        NaN  ...     NaN     NaN     NaN      NaN
23  4390.2025          NaN        NaN  ...     NaN     NaN     NaN      NaN
24  4395.9210          NaN        NaN  ...     NaN     NaN     NaN      NaN
25  4404.3445          NaN        NaN  ...     NaN     NaN     NaN      NaN
26  4406.8300          NaN        NaN  ...     NaN     NaN     NaN      NaN
27  4388.2640          NaN        NaN  ...     NaN     NaN     NaN      NaN
28  4333.6810          NaN        NaN  ...     NaN     NaN     NaN      NaN
29  4301.8090  4258.668000        NaN  ...     NaN     NaN     NaN      NaN
30  4272.0560  4239.663667        NaN  ...     NaN     NaN     NaN      NaN
31  4237.7210  4226.051000        NaN  ...     NaN     NaN     NaN      NaN
32  4210.0975  4222.552000        NaN  ...     NaN     NaN     NaN      NaN
33  4177.8425  4216.677000        NaN  ...     NaN     NaN     NaN      NaN
34  4136.5980  4212.810333        NaN  ...     NaN     NaN     NaN      NaN
35  4075.3520  4198.476667        NaN  ...     NaN     NaN     NaN      NaN
36  4031.5385  4181.205333        NaN  ...     NaN     NaN     NaN      NaN
37  3995.0845  4163.338333        NaN  ...     NaN     NaN     NaN      NaN
38  3973.0800  4142.649667        NaN  ...     NaN     NaN     NaN      NaN
39  3950.7940  4128.760000        NaN  ...     NaN     NaN     NaN      NaN
40  3913.9230  4114.504667        NaN  ...     NaN     NaN     NaN      NaN
41  3888.9925  4108.048333        NaN  ...     NaN     NaN     NaN      NaN
42  3883.5775  4094.282333        NaN  ...     NaN     NaN     NaN      NaN
43  3879.3715  4081.600667        NaN  ...     NaN     NaN     NaN      NaN
44  3891.7785  4070.054667        NaN  ...     NaN     NaN     NaN      NaN
45  3900.2790  4054.840333        NaN  ...     NaN     NaN     NaN      NaN
46  3911.0930  4051.769000        NaN  ...     NaN     NaN     NaN      NaN
47  3929.3585  4045.133000        NaN  ...     NaN     NaN     NaN      NaN
48  3980.3370  4048.749000        NaN  ...     NaN     NaN     NaN      NaN
49  4009.9585  4046.281000  4159.1842  ...     NaN     NaN     NaN      NaN

    MA_1010  MA_1020  MA_1030  MA_1040  MA_1050  MA_1060
0       NaN      NaN      NaN      NaN      NaN      NaN
1       NaN      NaN      NaN      NaN      NaN      NaN
2       NaN      NaN      NaN      NaN      NaN      NaN
3       NaN      NaN      NaN      NaN      NaN      NaN
4       NaN      NaN      NaN      NaN      NaN      NaN
5       NaN      NaN      NaN      NaN      NaN      NaN
6       NaN      NaN      NaN      NaN      NaN      NaN
7       NaN      NaN      NaN      NaN      NaN      NaN
8       NaN      NaN      NaN      NaN      NaN      NaN
9       NaN      NaN      NaN      NaN      NaN      NaN
10      NaN      NaN      NaN      NaN      NaN      NaN
11      NaN      NaN      NaN      NaN      NaN      NaN
12      NaN      NaN      NaN      NaN      NaN      NaN
13      NaN      NaN      NaN      NaN      NaN      NaN
14      NaN      NaN      NaN      NaN      NaN      NaN
15      NaN      NaN      NaN      NaN      NaN      NaN
16      NaN      NaN      NaN      NaN      NaN      NaN
17      NaN      NaN      NaN      NaN      NaN      NaN
18      NaN      NaN      NaN      NaN      NaN      NaN
19      NaN      NaN      NaN      NaN      NaN      NaN
20      NaN      NaN      NaN      NaN      NaN      NaN
21      NaN      NaN      NaN      NaN      NaN      NaN
22      NaN      NaN      NaN      NaN      NaN      NaN
23      NaN      NaN      NaN      NaN      NaN      NaN
24      NaN      NaN      NaN      NaN      NaN      NaN
25      NaN      NaN      NaN      NaN      NaN      NaN
26      NaN      NaN      NaN      NaN      NaN      NaN
27      NaN      NaN      NaN      NaN      NaN      NaN
28      NaN      NaN      NaN      NaN      NaN      NaN
29      NaN      NaN      NaN      NaN      NaN      NaN
30      NaN      NaN      NaN      NaN      NaN      NaN
31      NaN      NaN      NaN      NaN      NaN      NaN
32      NaN      NaN      NaN      NaN      NaN      NaN
33      NaN      NaN      NaN      NaN      NaN      NaN
34      NaN      NaN      NaN      NaN      NaN      NaN
35      NaN      NaN      NaN      NaN      NaN      NaN
36      NaN      NaN      NaN      NaN      NaN      NaN
37      NaN      NaN      NaN      NaN      NaN      NaN
38      NaN      NaN      NaN      NaN      NaN      NaN
39      NaN      NaN      NaN      NaN      NaN      NaN
40      NaN      NaN      NaN      NaN      NaN      NaN
41      NaN      NaN      NaN      NaN      NaN      NaN
42      NaN      NaN      NaN      NaN      NaN      NaN
43      NaN      NaN      NaN      NaN      NaN      NaN
44      NaN      NaN      NaN      NaN      NaN      NaN
45      NaN      NaN      NaN      NaN      NaN      NaN
46      NaN      NaN      NaN      NaN      NaN      NaN
47      NaN      NaN      NaN      NaN      NaN      NaN
48      NaN      NaN      NaN      NaN      NaN      NaN
49      NaN      NaN      NaN      NaN      NaN      NaN

[50 rows x 51 columns]

In [5]:
btc_data.columns

Index(['timestamp', 'open', 'high', 'low', 'close', 'volume', 'MA_10', 'MA_20',
       'MA_30', 'MA_50', 'MA_60', 'MA_90', 'MA_100', 'MA_110', 'MA_120',
       'MA_130', 'MA_140', 'MA_150', 'MA_160', 'MA_170', 'MA_180', 'MA_200',
       'MA_210', 'MA_220', 'MA_230', 'MA_240', 'MA_250', 'MA_260', 'MA_270',
       'MA_280', 'MA_290', 'MA_300', 'MA_450', 'MA_460', 'MA_470', 'MA_480',
       'MA_490', 'MA_500', 'MA_510', 'MA_520', 'MA_530', 'MA_540', 'MA_550',
       'MA_560', 'MA_1000', 'MA_1010', 'MA_1020', 'MA_1030', 'MA_1040',
       'MA_1050', 'MA_1060'],
      dtype='object')